import type { Metadata } from "next";
import { geistSans, geistMono } from "./fonts";
import "./globals.css";
import { UserFilterProvider } from "../app/context/user-filter-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <UserFilterProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </UserFilterProvider>
  );
}
